[package]
name = "php-parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
php-ast = { workspace = true }
php-lexer = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde = { workspace = true }
